-- paso1
drop table WORKER_3.C$_0STG_CLIENTE

-- paso2
create table WORKER_3.C$_0STG_CLIENTE
(
    NUM_NIT NUMBER(15,0),
    STR_RAZON_SOCIAL VARCHAR2(100),
    STR_SUCURSAL VARCHAR2(4),
    STR_RAZON_SOCIAL_SUCURSAL VARCHAR2(100),
    STR_TELEFONO VARCHAR2(15),
    STR_DIRECCION VARCHAR2(150),
    STR_CONTACTO_PRINCIPAL VARCHAR2(100),
    DT_FECHA_INGRESO DATE,
    STR_ANTIGUEDAD VARCHAR2(20),
    STR_CALIFICACION VARCHAR2(5),
    STR_CONDICION_DE_PAGO VARCHAR2(5),
    STR_DESC_CONDICION_DE_PAGO VARCHAR2(20),
    STR_CARTERA VARCHAR2(35),
    STR_FACTURACION VARCHAR2(25),
    STR_SECTOR_ECONOMICO VARCHAR2(6),
    STR_SERVICIO_QUE_PREDOMINA VARCHAR2(6),
    STR_TIPO_EMPRESA VARCHAR2(20)
)

--paso3
INSERT INTO WORKER_3.C$_0STG_CLIENTE (
    NUM_NIT,
    STR_RAZON_SOCIAL,
    STR_SUCURSAL,
    STR_RAZON_SOCIAL_SUCURSAL,
    STR_TELEFONO,
    STR_DIRECCION,
    STR_CONTACTO_PRINCIPAL,
    DT_FECHA_INGRESO,
    STR_ANTIGUEDAD,
    STR_CALIFICACION,
    STR_CONDICION_DE_PAGO,
    STR_DESC_CONDICION_DE_PAGO,
    STR_CARTERA,
    STR_FACTURACION,
    STR_SECTOR_ECONOMICO,
    STR_SERVICIO_QUE_PREDOMINA,
    STR_TIPO_EMPRESA 
    )
    VALUES(  
    :NUM_NIT  , 
    :STR_RAZON_SOCIAL  , 
    :STR_SUCURSAL  , 
    :STR_RAZON_SOCIAL_SUCURSAL  , 
    :STR_TELEFONO  , 
    :STR_DIRECCION  , 
    :STR_CONTACTO_PRINCIPAL  , 
    :DT_FECHA_INGRESO  , 
    :STR_ANTIGUEDAD  , 
    :STR_CALIFICACION  , 
    :STR_CONDICION_DE_PAGO  , 
    :STR_DESC_CONDICION_DE_PAGO  , 
    :STR_CARTERA  , 
    :STR_FACTURACION  , 
    :STR_SECTOR_ECONOMICO  , 
    :STR_SERVICIO_QUE_PREDOMINA  , 
    :STR_TIPO_EMPRESA 
    )


--paso4
drop table WORKER_3.I$_DIM_CLIENTE_SIN_FECHA   

--paso5
create table WORKER_3.I$_DIM_CLIENTE_SIN_FECHA
(
	SK_NUM_DIM_CLIENTE		NUMBER(7,0) NULL,
	NUM_NIT		NUMBER(15,0) NULL,
	STR_RAZON_SOCIAL		VARCHAR2(100) NULL,
	STR_SUCURSAL		VARCHAR2(4) NULL,
	STR_RAZON_SOCIAL_SUCURSAL		VARCHAR2(100) NULL,
	STR_TELEFONO		VARCHAR2(15) NULL,
	STR_DIRECCION		VARCHAR2(150) NULL,
	STR_CONTACTO_PRINCIPAL		VARCHAR2(100) NULL,
	DT_FECHA_INGRESO		DATE NULL,
	STR_ANTIGUEDAD		VARCHAR2(20) NULL,
	STR_CALIFICACION		VARCHAR2(5) NULL,
	STR_CONDICION_DE_PAGO		VARCHAR2(5) NULL,
	STR_DESC_CONDICION_DE_PAGO		VARCHAR2(20) NULL,
	STR_CARTERA		VARCHAR2(35) NULL,
	STR_FACTURACION		VARCHAR2(25) NULL,
	STR_SECTOR_ECONOMICO		VARCHAR2(6) NULL,
	STR_SERVICIO_QUE_PREDOMINA		VARCHAR2(6) NULL,
	STR_TIPO_EMPRESA		VARCHAR2(20) NULL,
	DT_FECHA_ACTUALIZACION		DATE NULL,
	IND_UPDATE		CHAR(1)
)
NOLOGGING  

--paso6
/* DETECTION_STRATEGY = NOT_EXISTS */
insert into	WORKER_3.I$_DIM_CLIENTE_SIN_FECHA
(
	NUM_NIT,
	STR_RAZON_SOCIAL,
	STR_SUCURSAL,
	STR_RAZON_SOCIAL_SUCURSAL,
	STR_TELEFONO,
	STR_DIRECCION,
	STR_CONTACTO_PRINCIPAL,
	DT_FECHA_INGRESO,
	STR_ANTIGUEDAD,
	STR_CALIFICACION,
	STR_CONDICION_DE_PAGO,
	STR_DESC_CONDICION_DE_PAGO,
	STR_CARTERA,
	STR_FACTURACION,
	STR_SECTOR_ECONOMICO,
	STR_SERVICIO_QUE_PREDOMINA,
	STR_TIPO_EMPRESA,
	IND_UPDATE
)
select 
NUM_NIT,
	STR_RAZON_SOCIAL,
	STR_SUCURSAL,
	STR_RAZON_SOCIAL_SUCURSAL,
	STR_TELEFONO,
	STR_DIRECCION,
	STR_CONTACTO_PRINCIPAL,
	DT_FECHA_INGRESO,
	STR_ANTIGUEDAD,
	STR_CALIFICACION,
	STR_CONDICION_DE_PAGO,
	STR_DESC_CONDICION_DE_PAGO,
	STR_CARTERA,
	STR_FACTURACION,
	STR_SECTOR_ECONOMICO,
	STR_SERVICIO_QUE_PREDOMINA,
	STR_TIPO_EMPRESA,
	IND_UPDATE
from (
select 	 
	STG_CLIENTE_A.NUM_NIT AS NUM_NIT,
	STG_CLIENTE_A.STR_RAZON_SOCIAL AS STR_RAZON_SOCIAL,
	STG_CLIENTE_A.STR_SUCURSAL AS STR_SUCURSAL,
	STG_CLIENTE_A.STR_RAZON_SOCIAL_SUCURSAL AS STR_RAZON_SOCIAL_SUCURSAL,
	STG_CLIENTE_A.STR_TELEFONO AS STR_TELEFONO,
	STG_CLIENTE_A.STR_DIRECCION AS STR_DIRECCION,
	STG_CLIENTE_A.STR_CONTACTO_PRINCIPAL AS STR_CONTACTO_PRINCIPAL,
	STG_CLIENTE_A.DT_FECHA_INGRESO AS DT_FECHA_INGRESO,
	STG_CLIENTE_A.STR_ANTIGUEDAD AS STR_ANTIGUEDAD,
	STG_CLIENTE_A.STR_CALIFICACION AS STR_CALIFICACION,
	STG_CLIENTE_A.STR_CONDICION_DE_PAGO AS STR_CONDICION_DE_PAGO,
	STG_CLIENTE_A.STR_DESC_CONDICION_DE_PAGO AS STR_DESC_CONDICION_DE_PAGO,
	STG_CLIENTE_A.STR_CARTERA AS STR_CARTERA,
	STG_CLIENTE_A.STR_FACTURACION AS STR_FACTURACION,
	STG_CLIENTE_A.STR_SECTOR_ECONOMICO AS STR_SECTOR_ECONOMICO,
	STG_CLIENTE_A.STR_SERVICIO_QUE_PREDOMINA AS STR_SERVICIO_QUE_PREDOMINA,
	STG_CLIENTE_A.STR_TIPO_EMPRESA AS STR_TIPO_EMPRESA,
	'I' IND_UPDATE
from	WORKER_3.C$_0STG_CLIENTE STG_CLIENTE_A
where	(1=1)
) S
where NOT EXISTS 
	( select 1 from WORKER_3.DIM_CLIENTE_SIN_FECHA T
	where	T.NUM_NIT	= S.NUM_NIT
	and	T.STR_SUCURSAL	= S.STR_SUCURSAL 
		and ((T.STR_RAZON_SOCIAL = S.STR_RAZON_SOCIAL) or (T.STR_RAZON_SOCIAL IS NULL and S.STR_RAZON_SOCIAL IS NULL)) and
		((T.STR_RAZON_SOCIAL_SUCURSAL = S.STR_RAZON_SOCIAL_SUCURSAL) or (T.STR_RAZON_SOCIAL_SUCURSAL IS NULL and S.STR_RAZON_SOCIAL_SUCURSAL IS NULL)) and
		((T.STR_TELEFONO = S.STR_TELEFONO) or (T.STR_TELEFONO IS NULL and S.STR_TELEFONO IS NULL)) and
		((T.STR_DIRECCION = S.STR_DIRECCION) or (T.STR_DIRECCION IS NULL and S.STR_DIRECCION IS NULL)) and
		((T.STR_CONTACTO_PRINCIPAL = S.STR_CONTACTO_PRINCIPAL) or (T.STR_CONTACTO_PRINCIPAL IS NULL and S.STR_CONTACTO_PRINCIPAL IS NULL)) and
		((T.DT_FECHA_INGRESO = S.DT_FECHA_INGRESO) or (T.DT_FECHA_INGRESO IS NULL and S.DT_FECHA_INGRESO IS NULL)) and
		((T.STR_ANTIGUEDAD = S.STR_ANTIGUEDAD) or (T.STR_ANTIGUEDAD IS NULL and S.STR_ANTIGUEDAD IS NULL)) and
		((T.STR_CALIFICACION = S.STR_CALIFICACION) or (T.STR_CALIFICACION IS NULL and S.STR_CALIFICACION IS NULL)) and
		((T.STR_CONDICION_DE_PAGO = S.STR_CONDICION_DE_PAGO) or (T.STR_CONDICION_DE_PAGO IS NULL and S.STR_CONDICION_DE_PAGO IS NULL)) and
		((T.STR_DESC_CONDICION_DE_PAGO = S.STR_DESC_CONDICION_DE_PAGO) or (T.STR_DESC_CONDICION_DE_PAGO IS NULL and S.STR_DESC_CONDICION_DE_PAGO IS NULL)) and
		((T.STR_CARTERA = S.STR_CARTERA) or (T.STR_CARTERA IS NULL and S.STR_CARTERA IS NULL)) and
		((T.STR_FACTURACION = S.STR_FACTURACION) or (T.STR_FACTURACION IS NULL and S.STR_FACTURACION IS NULL)) and
		((T.STR_SECTOR_ECONOMICO = S.STR_SECTOR_ECONOMICO) or (T.STR_SECTOR_ECONOMICO IS NULL and S.STR_SECTOR_ECONOMICO IS NULL)) and
		((T.STR_SERVICIO_QUE_PREDOMINA = S.STR_SERVICIO_QUE_PREDOMINA) or (T.STR_SERVICIO_QUE_PREDOMINA IS NULL and S.STR_SERVICIO_QUE_PREDOMINA IS NULL)) and
		((T.STR_TIPO_EMPRESA = S.STR_TIPO_EMPRESA) or (T.STR_TIPO_EMPRESA IS NULL and S.STR_TIPO_EMPRESA IS NULL))
        )

--paso7
/* DETECTION_STRATEGY = NOT_EXISTS */
update	WORKER_3.I$_DIM_CLIENTE_SIN_FECHA
set	IND_UPDATE = 'U'
where	(NUM_NIT, STR_SUCURSAL)
	in	(
		select	NUM_NIT,
			STR_SUCURSAL
		from	WORKER_3.DIM_CLIENTE_SIN_FECHA
		)

--paso8
/* DETECTION_STRATEGY = NOT_EXISTS */
update	WORKER_3.DIM_CLIENTE_SIN_FECHA T
set 	(
	T.STR_RAZON_SOCIAL,
	T.STR_RAZON_SOCIAL_SUCURSAL,
	T.STR_TELEFONO,
	T.STR_DIRECCION,
	T.STR_CONTACTO_PRINCIPAL,
	T.DT_FECHA_INGRESO,
	T.STR_ANTIGUEDAD,
	T.STR_CALIFICACION,
	T.STR_CONDICION_DE_PAGO,
	T.STR_DESC_CONDICION_DE_PAGO,
	T.STR_CARTERA,
	T.STR_FACTURACION,
	T.STR_SECTOR_ECONOMICO,
	T.STR_SERVICIO_QUE_PREDOMINA,
	T.STR_TIPO_EMPRESA
	,               T.DT_FECHA_ACTUALIZACION
	) =
		(
		select	S.STR_RAZON_SOCIAL,
			S.STR_RAZON_SOCIAL_SUCURSAL,
			S.STR_TELEFONO,
			S.STR_DIRECCION,
			S.STR_CONTACTO_PRINCIPAL,
			S.DT_FECHA_INGRESO,
			S.STR_ANTIGUEDAD,
			S.STR_CALIFICACION,
			S.STR_CONDICION_DE_PAGO,
			S.STR_DESC_CONDICION_DE_PAGO,
			S.STR_CARTERA,
			S.STR_FACTURACION,
			S.STR_SECTOR_ECONOMICO,
			S.STR_SERVICIO_QUE_PREDOMINA,
			S.STR_TIPO_EMPRESA
			,               SYSDATE
		from	WORKER_3.I$_DIM_CLIENTE_SIN_FECHA S
		where	T.NUM_NIT	=S.NUM_NIT
		and	T.STR_SUCURSAL	=S.STR_SUCURSAL
    	)
where	(NUM_NIT, STR_SUCURSAL)
	in	(
		select	NUM_NIT,
			STR_SUCURSAL
		from	WORKER_3.I$_DIM_CLIENTE_SIN_FECHA
		where	IND_UPDATE = 'U'
		)

--paso9
/* DETECTION_STRATEGY = NOT_EXISTS */
insert into 	WORKER_3.DIM_CLIENTE_SIN_FECHA T
	(
	NUM_NIT,
	STR_RAZON_SOCIAL,
	STR_SUCURSAL,
	STR_RAZON_SOCIAL_SUCURSAL,
	STR_TELEFONO,
	STR_DIRECCION,
	STR_CONTACTO_PRINCIPAL,
	DT_FECHA_INGRESO,
	STR_ANTIGUEDAD,
	STR_CALIFICACION,
	STR_CONDICION_DE_PAGO,
	STR_DESC_CONDICION_DE_PAGO,
	STR_CARTERA,
	STR_FACTURACION,
	STR_SECTOR_ECONOMICO,
	STR_SERVICIO_QUE_PREDOMINA,
	STR_TIPO_EMPRESA
	,SK_NUM_DIM_CLIENTE,
	DT_FECHA_ACTUALIZACION
	)
select 	NUM_NIT,
	STR_RAZON_SOCIAL,
	STR_SUCURSAL,
	STR_RAZON_SOCIAL_SUCURSAL,
	STR_TELEFONO,
	STR_DIRECCION,
	STR_CONTACTO_PRINCIPAL,
	DT_FECHA_INGRESO,
	STR_ANTIGUEDAD,
	STR_CALIFICACION,
	STR_CONDICION_DE_PAGO,
	STR_DESC_CONDICION_DE_PAGO,
	STR_CARTERA,
	STR_FACTURACION,
	STR_SECTOR_ECONOMICO,
	STR_SERVICIO_QUE_PREDOMINA,
	STR_TIPO_EMPRESA
	,WORKER_3.SEQ_DIM_CLIENTE.NEXTVAL,
	SYSDATE
from	WORKER_3.I$_DIM_CLIENTE_SIN_FECHA S
where	IND_UPDATE = 'I'

--paso10