1. SELECT * FROM estudiantes;
2. SELECT * 
    FROM ESTUDIANTES
    WHERE CARRERA = 'INGENIERIA';
3. SELECT *
    FROM ESTUDIANTES
    ORDER BY PROMEDIO DESC;
4. SELECT *
    FROM ESTUDIANTES
    WHERE EDAD > 20;
5. SELECT *
    FROM ESTUDIANTES
    WHERE CARRERA = 'MEDICINA'
    ORDER BY PROMEDIO ASC;

--RESPUESTAS
-- ORDENA DE MYOR A MENOR LOS REGISTROS
-- EN EL CASO DE LOS ESTUDIANTES DE INGENIERIA HAY DOS,Y MAYOROS QUE 20 HAY 3
