/*
########## Creado por: Sebastian Carrero ##########
########## Fecha De Creacion: 6/12/24 #############
########## Dimension Cliente, encargada de almacenar los datos de los clientes #############
*/

CREATE TABLE DIM_CLIENTE (
    SK_NUM_DIM_CLIENTE NUMBER(7),
    NUM_NIT NUMBER(15) NOT NULL,    
    STR_RAZON_SOCIAL VARCHAR2(100), 
    STR_SUCURSAL VARCHAR2(4) NOT NULL, 
    STR_RAZON_SOCIAL_SUCURSAL VARCHAR2(100),
    STR_TELEFONO VARCHAR2(15), 
    STR_DIRECCION VARCHAR2(150), 
    STR_CONTACTO_PRINCIPAL VARCHAR2(100), 
    DT_FECHA_INGRESO DATE, 
    STR_ANTIGUEDAD VARCHAR2(20), 
    STR_CALIFICACION VARCHAR2(5), 
    STR_CONDICION_DE_PAGO VARCHAR2(5), 
    STR_DESC_CONDICION_DE_PAGO VARCHAR2(20), 
    STR_CARTERA VARCHAR2(35), 
    STR_FACTURACION VARCHAR2(25), 
    STR_SECTOR_ECONOMICO VARCHAR2(6), 
    STR_SERVICIO_QUE_PREDOMINA VARCHAR2(6), 
    STR_TIPO_EMPRESA VARCHAR2(20), 
    DT_FECHA_INSERCION DATE,
    DT_FECHA_ACTUALIZACION DATE,
    DT_FECHA_FIN DATE
);

/*########## Indice Unico Compuesto #########*/
CREATE UNIQUE INDEX IDX_NIT_STR_SUCURSAL
ON DIM_CLIENTE (NUM_NIT, STR_SUCURSAL);


/*########## Secuencia #########*/
CREATE SEQUENCE SEQ_SK_DIM_CLIENTE
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;


CREATE OR REPLACE TRIGGER TRG_ACTUALIZAR_FECHA_DIM_CLIENTE
BEFORE UPDATE ON DIM_CLIENTE
FOR EACH ROW
WHEN (OLD.STR_RAZON_SOCIAL != NEW.STR_RAZON_SOCIAL OR
        OLD.STR_RAZON_SOCIAL_SUCURSAL != NEW.STR_RAZON_SOCIAL_SUCURSAL OR
        OLD.STR_TELEFONO != NEW.STR_TELEFONO OR
        OLD.STR_DIRECCION != NEW.STR_DIRECCION OR
        OLD.STR_CONTACTO_PRINCIPAL != NEW.STR_CONTACTO_PRINCIPAL OR
        OLD.STR_ANTIGUEDAD != NEW.STR_ANTIGUEDAD OR
        OLD.STR_CALIFICACION != NEW.STR_CALIFICACION OR
        OLD.STR_CONDICION_DE_PAGO != NEW.STR_CONDICION_DE_PAGO OR
        OLD.STR_DESC_CONDICION_DE_PAGO != NEW.STR_DESC_CONDICION_DE_PAGO OR
        OLD.STR_CARTERA != NEW.STR_CARTERA OR
        OLD.STR_FACTURACION != NEW.STR_FACTURACION OR
        OLD.STR_SECTOR_ECONOMICO != NEW.STR_SECTOR_ECONOMICO OR
        OLD.STR_SERVICIO_QUE_PREDOMINA != NEW.STR_SERVICIO_QUE_PREDOMINA OR
        OLD.STR_TIPO_EMPRESA != NEW.STR_TIPO_EMPRESA
)
BEGIN    
    :NEW.DT_FECHA_ACTUALIZACION := SYSDATE;
END;
/