/*
########## Creado por: Sebastian Carrero ###########
########## Fecha De Creacion: 27/03/25 #############
########## STG_FAC_FINANCIENRA #####################
*/

/*=======================================================
########## STAGING FINANCIERA ##########
=========================================================*/
CREATE TABLE STG_FAC_FINANCIERA(	
    NUM_ID_CIA NUMBER(3), 
	STR_RAZON_SOCIAL VARCHAR2(80), 
	NUM_ID_CCOSTO_MAYOR NUMBER(7),
	STR_ID_CENTRO_COSTO VARCHAR2(25), 
	STR_CENTRO_COSTO_NOMBRE VARCHAR2(50), 
	STR_TERCERO_ID VARCHAR2(15), 
	STR_TERCERO_NIT VARCHAR2(25), 
	STR_TERCERO_NOMBRE VARCHAR2(120), 
	STR_ID_SUCURSAL VARCHAR2(5),
	NUM_PERIODO_FECHA NUMBER(7), 
	DT_FECHA_DOCTO DATE, 
	NUM_LINEA_ID_MOVTO NUMBER(9), 
	NUM_DEBITO NUMBER(19,2), 
	NUM_CREDITO NUMBER(19,2), 
	NUM_LINEA_ID_DOCTO NUMBER(8), 
	STR_ID_TIPO_DOCTO VARCHAR2(3), 
	STR_DESCRIPCION_DOCTO VARCHAR2(40), 
	STR_PLAN_CUENTAS VARCHAR2(3), 
	STR_CUENTA_PADRE VARCHAR2(20), 
	NUM_CUENTA_MAYOR NUMBER(8), 
	STR_CUENTA_AUXILIAR VARCHAR2(20), 
	STR_DESCRIPCION_CUENTA VARCHAR2(42), 
	NUM_DOCTO_AUXILIAR NUMBER(8), 
	STR_AUXILIAR_DESCRIPCION VARCHAR2(50), 
	STR_CODIGO_PRODUCTO VARCHAR2(20), 
	STR_DESCRIPCION_SERVICIO VARCHAR2(45), 
	NUM_CODIGO_SECTOR NUMBER(6),
	NUM_NRO_DOCTO NUMBER(11),
	NUM_ID_CCOSTO NUMBER(8)
);
